# Generated by Django 3.0.5 on 2020-04-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspectedcase',
            name='symptoms_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
